# Generated by Django 4.1.5 on 2023-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
