# Generated by Django 4.1.5 on 2023-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
