# Generated by Django 4.1.5 on 2023-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_users_id_users_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_user',
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
