# Generated by Django 4.1.5 on 2023-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_project_name_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.JSONField()),
                ('name', models.CharField(max_length=20)),
                ('image', models.FilePathField()),
                ('sound', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('frequency', models.IntegerField()),
                ('sound', models.FilePathField()),
                ('image', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('user_image', models.FilePathField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
