# Generated by Django 4.1.5 on 2023-02-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chords_notes_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chords',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
