# Generated by Django 4.1.5 on 2023-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='image',
            field=models.FilePathField(default="{% static '' %}"),
            preserve_default=False,
        ),
    ]
