# Generated by Django 4.1.5 on 2023-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lessons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(upload_to='static/lessons_images/'),
        ),
    ]
