# Generated by Django 4.1.5 on 2023-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lessons_description_alter_lessons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.TextField(),
        ),
    ]
